

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/navbar";
import AppContextProvider from "@/context";
import CartComponents from "@/components/Cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full overflow-x-hidden m-0 `}>
        <AppContextProvider>
          <Navbar />
          <CartComponents />
          <main>{children}</main>
        </AppContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
